### ISSUE TITLE
compilation error - function 'new' not found in Config<_>

### ISSUE THREAD

**Issue by jbovet** [open-feature/rust-sdk-contrib#17]
This error suggests that the [new](https://github.com/open-feature/rust-sdk-contrib/blob/6385382bbffb2154b45044cf69f00f4f63ea0862/crates/flipt/src/flipt.rs#L42) function is not found for the `flipt::Config` struct related to the `flipt` crate.

# How to reproduce
run test for workspace 
* `cargo test --workspace `

or running tests inside crate
* `cd crates/flipt/ && cargo test`

```rust
error[E0599]: no function or associated item named `new` found for struct `flipt::Config` in the current scope
--> crates/flipt/src/flipt.rs:42:43
|
42 |    let flipt_config = flipt::Config::new(url, config.authentication_strategy, config.timeout);
|                      ^^^ function or associated item not found in `Config<_>`
``` 
# Github action
https://github.com/jbovet/rust-sdk-contrib/actions/runs/9309610680/job/25625393051

Let me know if you need any additional information.

**Comment by tamaroning** [comment]
it seems that the flipt library changed its interface regardless of its minor semver change.
I am trying to fix it.
