### ISSUE TITLE
Add flipt provider

### ISSUE THREAD

**Issue by tamaroning** [open-feature/rust-sdk-contrib#6]
Hello, I am new to OpenFeature.
I am thinking of adding Flipt provider.
It seems that there is not any provider implementation yet.
please let me know if there are instructions to follow (e.g. directory structure)

**Comment by sheepduke** [comment]
IMHO it is better to make this project a workspace and create one directory for each contrib. What do you think?

**Comment by beeme1mr** [comment]
Yes, that's what we've done in other contribs repos. I can try and help from a tooling perspective.

**Comment by sheepduke** [comment]
@beeme1mr Do other contribs repos have an umbrella project for all the contribs? I am re-thinking if we should have a "root" crate as a workspace, or simply make each contrib (directory) individual.

**Comment by beeme1mr** [comment]
@sheepduke most contribs repos publish under an OpenFeature project or org. I'm not sure how that would work in Rust but we should try and do something similar if possible.

**Comment by tamaroning** [comment]
completed via https://github.com/open-feature/rust-sdk-contrib/pull/8
